### PR TITLE
Native xorg support in Freon

### LINKED ISSUE #1265: Need Freon support in xorg
Hello,

   I've tried installing Ubuntu Trusty & Precise on my Acer C720-3404 twice. In between installs I turned Developer Mode off to clear any previous installs. I've used the following commands:

<code>
sudo sh -e ~/Downloads/crouton -t unity (1st attempt - precise)
</code>
<code>
sudo sh -e ~/Downloads/crouton -r trusty -t unity (2nd attempt - trusty)
</code>

As far as I can tell, there are no errors during installation, but every time I try to initiate unity (sudo startunity) I get the following error:

<code>
xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
</code>

I appreciate any help and I will post the entire initialization at the bottom of this post.

Regards,
Vialeport

/dev files:
<code>
chronos@localhost /dev $ dir
</code>

<code>
block             core               dm-1  hwrng   i2c-5  log    loop6         network_latency     ptmx    sda1   sda5  stderr  uhid     vhci
bsg               cpu                dri   i2c-0   i2c-6  loop0  loop7         network_throughput  pts     sda10  sda6  stdin   uinput   video0
bus               cpu_dma_latency    fb0   i2c-1   i2c-7  loop1  loop-control  null                random  sda11  sda7  stdout  urandom  zero
bus_throughput    cros_ec            fd    i2c-10  i2c-8  loop2  mapper        nvram               rfkill  sda12  sda8  tpm0    usbmon0  zram0
char              device_throughput  full  i2c-2   i2c-9  loop3  mcelog        port                rtc     sda2   sda9  tty     usbmon1
chromeos-low-mem  disk               fuse  i2c-3   input  loop4  mem           ppp                 rtc0    sda3   shm   tty1    usbmon2
console           dm-0               hpet  i2c-4   kmsg   loop5  net           pstore              sda     sda4   snd   tty8    v4l
</code>

Entire log:
<frame>
X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 17 20:15:28 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=75bae8b0-f99d-5843-9de2-1f73b28f3080/PARTNROFF=1 hashtree=PARTUUID=75bae8b0-f99d-5843-9de2-1f73b28f3080/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0035a6e81c87a14f2728ce7656a72489fc70c348 salt=635f605833ed8caf164b114f1ff1dece71e6d076b9881db47cf7f086302dca7e" noinitrd vt.global_cursor_default=0 kern_guid=75bae8b0-f99d-5843-9de2-1f73b28f3080 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 
Build Date: 10 December 2014  06:15:52PM
xorg-server 2:1.15.1-0ubuntu2.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Dec 20 17:44:30 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

</frame>

### PR DESCRIPTION
**Pull request by dnschneid**
Fixes #1265. Also merges in the armxorg branch, partially fixing #1089, and enables SNA+Tearfree, fixing #520.

### CODE REVIEW

File: installer/prepare.sh [hunk 1]
```diff
@@ -176,19 +176,25 @@ fixkeyboardmode() {
...
 # increasing the size of the chroot after install.
-# $1: name; target is /usr/local/bin/crouton$1
+# $1: name; target is /usr/local/(bin|lib)/crouton$1[.so]
 # $2: linker flags, quoted together
+# [$3]: if 'so', compiles as a shared object and installs it into lib
 # $3+: any package dependencies other than gcc and libc-dev, crouton-style.
 compile() {
-    local out="/usr/local/bin/crouton$1" linker="$2"
-    echo "Installing dependencies for $out..." 1>&2
+    local out="/usr/local/bin/crouton$1" linker="$2" cflags='-xc -Os'
```
Comment (drinkcat) [inline installer/prepare.sh]: One variable per line, for clarity?

File: chroot-bin/croutoncycle [hunk 2]
```diff
@@ -97,27 +94,30 @@ for disp in /tmp/.X*-lock; do
     fi
 done
 
-# host-x11 fails if no Chromium OS server exist
-if host-x11 true 2>/dev/null; then
+# Set to the freon display owner if freon is used
+freonowner=''
+if [ ! -f "/sys/class/tty/tty0/active" ]; then
+    if [ -f "/tmp/crouton-lock/display" ]; then
+        read freonowner < "/tmp/crouton-lock/display"
```
Comment (drinkcat) [inline chroot-bin/croutoncycle]: `read -r`, for consistency... (not that it really matters here)

File: chroot-bin/croutoncycle [hunk 3]
```diff
@@ -307,6 +328,15 @@ else
...
         sudo -n chvt "$dest"
+    else
+        dest="/tmp/.X${destdisp#:}-lock"
+        if [ -f "$dest" ]; then
+            # Trigger the target before releasing the current owner
+            kill -USR1 `cat /tmp/.X${destdisp#:}-lock`
+        fi
+        if [ "${freonowner:-0}" != 0 ]; then
+            kill -USR1 "$freonowner"
+        fi
```
Comment (drinkcat) [inline chroot-bin/croutoncycle]: If I remember correctly how switching works (X server crashes if it cannot obtain DRM master), this feels race-prone (I'm actually surprised this works at all...)... Does it work if you add a sleep in between the 2 statements?

File: chroot-bin/croutonxinitrc-wrapper [hunk 4]
```diff
@@ -78,7 +78,42 @@ if [ "$XMETHOD" = 'xephyr' ]; then
...
+KEY_F2+KEY_LEFTSHIFT+KEY_LEFTCTRL+KEY_LEFTALT@ 1 @n
+KEY_F2@n 0 $cmdnext
+KEY_LEFTSHIFT@n 0 $cmdnext
+KEY_LEFTCTRL@n 0 $cmdnext
+KEY_LEFTALT@n 0 $cmdnext
+KEY_F2@n 0 @
+KEY_LEFTSHIFT@n 0 @
+KEY_LEFTCTRL@n 0 @
+KEY_LEFTALT@n 0 @
+#" | /usr/sbin/thd --triggers /dev/stdin \
```
Comment (drinkcat) [inline chroot-bin/croutonxinitrc-wrapper]: Neat... Only issue is that there is no Arch package for it....

File: host-bin/enter-chroot [hunk 5]
```diff
@@ -654,6 +646,27 @@ if [ ! "$NOLOGIN" = 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
...
+    # FIXME: remove when crbug.com/457075 is resolved
+    if [ -f /sbin/frecon ]; then
+        mkdir -p "$CROUTONLOCKDIR"
+        chmod 777 "$CROUTONLOCKDIR"
+        if [ ! -e "$CROUTONLOCKDIR/frecon" ]; then
+            mkfifo "$CROUTONLOCKDIR/frecon"
+            chmod 622 "$CROUTONLOCKDIR/frecon"
+        fi
+        chrootcmd "(exec >/dev/null 2>&1 </dev/null
+            while read cmd <'$CROUTONLOCKDIR/frecon'; do
```
Comment (drinkcat) [inline host-bin/enter-chroot]: -r

File: chroot-bin/croutoncycle (hunk 3 above)
Comment (drinkcat) [inline chroot-bin/croutoncycle]: Ah, I get it, the LD_PRELOAD hack makes it work nice. Cool.

File: src/freon.c [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+            struct vt_stat* stat = data;
+            stat->v_active = 0;
+        }
+
+        if ((request == VT_RELDISP && (long)data == 1) ||
+            (request == VT_ACTIVATE && (long)data == 0)) {
+            if (lockfd != -1) {
+                TRACE("Telling Chromium OS to regain control\n");
+                ret = FREON_DBUS_METHOD_CALL(TakeDisplayOwnership);
+                if (set_display_lock(0)) {
```
Comment (drinkcat) [inline src/freon.c]: < 0

File: src/freon.c [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+                    ERROR("Failed to release display lock\n");
+                }
+            }
+        } else if ((request == VT_RELDISP && (long)data == 2) ||
+                   (request == VT_ACTIVATE && (long)data == 7)) {
+            if (!set_display_lock(getpid())) {
```
Comment (drinkcat) [inline src/freon.c]: == 0

File: src/freon.c [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+
+static void preload_init() {
+    orig_ioctl = dlsym(RTLD_NEXT, "ioctl");
+    orig_open = dlsym(RTLD_NEXT, "open");
+    orig_close = dlsym(RTLD_NEXT, "close");
+}
+
+static int set_display_lock(unsigned int pid) {
+    if (lockfd == -1) {
+        if (!pid) {
```
Comment (drinkcat) [inline src/freon.c]: == 0

File: src/freon.c [hunk 9]
```diff
@@ -0,0 +1,186 @@
...
+    int len;
+    if ((len = snprintf(buf, sizeof(buf), "%d\n", pid)) < 0) {
+        ERROR("pid sprintf failed.\n");
+        return -1;
+    }
+    if (write(lockfd, buf, len) == -1) {
+        ERROR("Unable to write to display lock file.\n");
+        return -1;
+    }
+    if (!pid) {
```
Comment (drinkcat) [inline src/freon.c]: == 0

File: src/freon.c [hunk 10]
```diff
@@ -0,0 +1,186 @@
...
+static int (*orig_open)(const char *pathname, int flags, mode_t mode);
+static int (*orig_close)(int fd);
+
+static void preload_init() {
+    orig_ioctl = dlsym(RTLD_NEXT, "ioctl");
+    orig_open = dlsym(RTLD_NEXT, "open");
+    orig_close = dlsym(RTLD_NEXT, "close");
+}
+
+static int set_display_lock(unsigned int pid) {
```
Comment (drinkcat) [inline src/freon.c]: Add a short description of the function, stating that pid == 0 is a special case.

File: chroot-bin/croutoncycle (hunk 3 above)
Comment (dnschneid) [inline chroot-bin/croutoncycle]: Yeah, magical flocks o' locks, followed by signal ordering abuse to give Chrome as little time as possible to render anything :)

File: chroot-bin/croutonxinitrc-wrapper (hunk 4 above)
Comment (dnschneid) [inline chroot-bin/croutonxinitrc-wrapper]:
```
#!/bin/sh -e
# hexdump output format variables
SECONDS_LO='$1'
SECONDS_HI='$2'
USECONDS_LO='$3'
USECONDS_HI='$4'
TYPE='$5'
KEY='$6'
STATE='$7'
# constants
TYPE_EV_KEY=1
STATE_DOWN=1
STATE_UP=0
KEY_LEFTCTRL=29
KEY_LEFTALT=56
KEY_LEFTSHIFT=42
KEY_F1=59
KEY_F2=60
# Read in the event file and split it into input_event fields
stdbuf -oL hexdump -e '4/4 "%u " " " 2/2 "%u " " " 1/4 "%u " "\n"' /dev/input/event3 \
| awk -W interactive "
    function update() {
        if (!cmd && c && s && a && p) {
            cmd = \"p\"
        } else if (!cmd && c && s && a && n) {
            cmd = \"n\"
        } else if (cmd && !c && !s && !a && !p && !n) {
            system(\"croutoncycle \" cmd)
            cmd = \"\"
        }
    }
    $TYPE == $TYPE_EV_KEY && $KEY == $KEY_LEFTCTRL  { c = $STATE; update() }
    $TYPE == $TYPE_EV_KEY && $KEY == $KEY_LEFTSHIFT { s = $STATE; update() }
    $TYPE == $TYPE_EV_KEY && $KEY == $KEY_LEFTALT   { a = $STATE; update() }
    $TYPE == $TYPE_EV_KEY && $KEY == $KEY_F1        { p = $STATE; update() }
    $TYPE == $TYPE_EV_KEY && $KEY == $KEY_F2        { n = $STATE; update() }
"
```
...so simple it's sad

Comment (dnschneid) [inline chroot-bin/croutonxinitrc-wrapper]: Anyway, expanded that to monitor all event files (and watch for new ones), so we're good to go.
Side benefit: this can probably be used to monitor for things like lid switch events.

**Comment by dnschneid** [comment]
@drinkcat I think everything's good to go?

**Comment by alfonsojon** [comment]
Not exactly pertinent to the pull request itself, but will this allow for acceleration on Exynos platforms, such as the HP Chromebook 11? Thanks.

**Comment by dnschneid** [comment]
@alfonsojon probably not.  It will enable somewhat better performance than xephyr (and avoid its various oddities).  It's possible that the improved handoff will make the mali driver work (and it's worth trying out), but I wouldn't get your hopes up.

**Comment by alfonsojon** [comment]
@dnschneid Alright, either way, I'm happy to test if you need a test system.

**Comment by reeved** [comment]
The latest Dev Channel update breaks this feature.  Heres what it says when I try to enter my XFCE desktop:

sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xfce...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Feb 25 12:34:13 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=d72cbb79-d7bf-1044-8661-7dc1e0bc33a8/PARTNROFF=1 hashtree=PARTUUID=d72cbb79-d7bf-1044-8661-7dc1e0bc33a8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=1853f470afe12bfd6b8b893f8d1c935bd80ea480 salt=46e20aa7408a50d445420ea27b56b05a5b4317892e1b48116e5190f719f34d23" noinitrd vt.global_cursor_default=0 kern_guid=d72cbb79-d7bf-1044-8661-7dc1e0bc33a8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.28391.log", Time: Fri Feb 27 15:37:44 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f6cc7a88848]
(EE) 1: /usr/bin/Xorg (0x7f6cc78df000+0x1ad539) [0x7f6cc7a8c539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f6cc67d9000+0x10340) [0x7f6cc67e9340]
(EE) 3: /usr/bin/Xorg (0x7f6cc78df000+0xb57a6) [0x7f6cc79947a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f6cc7968099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f6cc79766fd]
(EE) 6: /usr/bin/Xorg (0x7f6cc78df000+0x59bab) [0x7f6cc7938bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f6cc5219ec5]
(EE) 8: /usr/bin/Xorg (0x7f6cc78df000+0x451ee) [0x7f6cc79241ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.28391.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...

**Comment by dnschneid** [comment]
See #1443.  Update your chroot and it should work.
