### PR TITLE
Use updated dbus method calls

### LINKED ISSUE #3375: Can't Initialize ubuntu with crouton
crosh> shell 
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.79-11537-ga1d73b70a6f1 #1 SMP PREEMPT Mon Aug 28 03:09:13 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashtree=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=98b12ddf2d5e154833ef89a3d7eb0a2b6b5678a2 salt=6bbf8d3c714ce08b545d8f5595ad3d9709caa853452cfaa2d2cfeec9c27d9f8f" noinitrd vt.global_cursor_default=0 kern_guid=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Aug 29 18:09:16 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.

### PR DESCRIPTION
**Pull request by farmerbb**
Fixes #3375

Due to dbus interface changes in Chrome OS, if one dbus method call fails, then run the other one right after.

### CODE REVIEW

**Comment by farmerbb** [comment]
I signed it!

File: src/freon.c [hunk 1]
```diff
@@ -29,6 +29,10 @@
     system("host-dbus dbus-send --system --dest=org.chromium.LibCrosService " \
```
Comment (dnschneid) [inline src/freon.c]: how about renaming this one to LIBCROSSERVICE_METHOD_CALL

File: src/freon.c [hunk 2]
```diff
@@ -29,6 +29,10 @@
...
            "--type=method_call --print-reply /org/chromium/LibCrosService " \
            "org.chromium.LibCrosServiceInterface." #function)
+#define FREON_DBUS_METHOD_CALL_NEW(function) \
```
Comment (dnschneid) [inline src/freon.c]: this one can be DISPLAYSERVICE_METHOD_CALL

File: src/freon.c [hunk 3]
```diff
@@ -163,6 +167,9 @@ int ioctl(int fd, unsigned long int request, ...) {
             if (lockfd != -1) {
                 TRACE("Telling Chromium OS to regain control\n");
                 ret = FREON_DBUS_METHOD_CALL(TakeDisplayOwnership);
+                if (WEXITSTATUS(ret) == 1) {
```
Comment (dnschneid) [inline src/freon.c]: will it always be 1? or just non-zero?

File: src/freon.c (hunk 1 above)
Comment (farmerbb) [reply src/freon.c]: Done.

File: src/freon.c (hunk 2 above)
Comment (farmerbb) [reply src/freon.c]: Done.

File: src/freon.c (hunk 3 above)
Comment (farmerbb) [reply src/freon.c]: Looks like it will always exit with 1 when an error occurs: https://cgit.freedesktop.org/dbus/dbus/tree/tools/dbus-send.c#n593
